iec_price: 0.6402 # shekels per kWh
rounding_digits: 2
plans:
  - name: None
    discount: 0
    hours: []
    color:
      light: "rgba(174, 223, 247, 1)"    # #AEDFF7
      dark: "rgba(174, 223, 247, 0.2)"
  - name: Night
    discount: 0.2
    hours: [0, 1, 2, 3, 4, 5, 6, 23]
    color:
      light: "rgba(182, 247, 174, 1)"    # #B6F7AE
      dark: "rgba(182, 247, 174, 0.2)"
  - name: Power
    discount: 0.065
    hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
    color:
      light: "rgba(247, 230, 174, 1)"    # #F7E6AE
      dark: "rgba(247, 230, 174, 0.2)"
  - name: Hightech
    discount: 0.1
    hours: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,23]
    color:
      light: "rgba(247, 174, 207, 1)"    # #F7AECF
      dark: "rgba(247, 174, 207, 0.2)"